# Generated by Django 2.2 on 2019-04-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('climate', models.CharField(max_length=200)),
                ('terrain', models.CharField(max_length=200)),
                ('movie_appearance', models.IntegerField()),
            ],
        ),
    ]
