# Generated by Django 2.2 on 2019-04-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='nome',
            new_name='name',
        ),
    ]
